# Generated by Django 4.0.3 on 2022-05-10 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('carts', '0002_carditem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='CardItem',
            new_name='CartItem',
        ),
    ]
